### ISSUE TITLE
Startup fails with `detailed_middleware: true` option

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/scout_apm_ruby#170]
If I set the the config option `detailed_middleware: true`, `rails s` fails with the following exception:

```
/Users/dlite/.rvm/gems/ruby-2.1.2/gems/scout_apm-3.0.0.pre20/lib/scout_apm/instruments/middleware_detailed.rb:33:in `build': undefined local variable or method `logger' for ServerTiming::Middleware:ActionDispatch::MiddlewareStack::Middleware (NameError)
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/stack.rb:118:in `block in build'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/stack.rb:118:in `each'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/stack.rb:118:in `inject'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/stack.rb:118:in `build'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/railties-4.2.7.1/lib/rails/engine.rb:502:in `app'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/railties-4.2.7.1/lib/rails/application/finisher.rb:34:in `block in <module:Finisher>'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/dlite/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
	from /Users/dlite/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/dlite/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
	from /Users/dlite/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/dlite/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each'
	from /Users/dlite/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `call'
	from /Users/dlite/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/dlite/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
	from /Users/dlite/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
	from /Users/dlite/projects/apm/config/environment.rb:5:in `<top (required)>'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/dlite/projects/apm/config.ru:3:in `block in <main>'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/rack-1.6.5/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/rack-1.6.5/lib/rack/builder.rb:55:in `initialize'
	from /Users/dlite/projects/apm/config.ru:in `new'
	from /Users/dlite/projects/apm/config.ru:in `<main>'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/rack-1.6.5/lib/rack/builder.rb:49:in `eval'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/rack-1.6.5/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/rack-1.6.5/lib/rack/builder.rb:40:in `parse_file'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/rack-1.6.5/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/rack-1.6.5/lib/rack/server.rb:208:in `app'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/railties-4.2.7.1/lib/rails/commands/server.rb:61:in `app'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/rack-1.6.5/lib/rack/server.rb:336:in `wrapped_app'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/railties-4.2.7.1/lib/rails/commands/server.rb:139:in `log_to_stdout'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/railties-4.2.7.1/lib/rails/commands/server.rb:78:in `start'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/dlite/projects/apm/bin/rails:9:in `require'
	from /Users/dlite/projects/apm/bin/rails:9:in `<top (required)>'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	from /Users/dlite/.rvm/gems/ruby-2.1.2/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	from /Users/dlite/projects/apm/bin/spring:15:in `require'
	from /Users/dlite/projects/apm/bin/spring:15:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

As a sanity check, I removed the Server Timing middleware and the exception still occurs.

**Comment by cschneid** [comment]
This was fixed in c8220aae85aa8cb49c1553dd6244bf5d4b8115dc - but it looks like it hasn't been released into a `3.0.0.preX` release yet. It will be in the next one.
