### ISSUE TITLE
rusage.so: file too short

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout_apm_ruby#176]
A customer ran into an issue with the rusage.so shared library that is built at gem install time. 

```
LoadError: /home/ubuntu/apps/<the app>/shared/bundle/ruby/2.4.0/gems/scout_apm-3.0.0.pre20/lib/rusage.so: file too short - /home/ubuntu/apps/<the app>/shared/bundle/ruby/2.4.0/gems/scout_apm-3.0.0.pre20/lib/rusage.so
/home/ubuntu/apps/<the app>/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
/home/ubuntu/apps/<the app>/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `block in require'
/home/ubuntu/apps/<the app>/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/ubuntu/apps/<the app>/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
/home/ubuntu/apps/<the app>/shared/bundle/ruby/2.4.0/gems/scout_apm-3.0.0.pre20/lib/scout_apm.rb:22:in `<top (required)>'
```

**Comment by sixfeetover** [comment]
The file exists, and is non-empty:

```
$ file rusage.so
rusage.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=43876e8917b5551c5c8a6d31f89a5d57f577d51e, not stripped
```

```
$ stat rusage.so
  File: 'rusage.so'
  Size: 67272     	Blocks: 136        IO Block: 4096   regular file
Device: ca01h/51713d	Inode: 1029907     Links: 1
Access: (0755/-rwxr-xr-x)  Uid: ( 1000/  ubuntu)   Gid: ( 1000/  ubuntu)
Access: 2018-03-28 16:42:51.459780747 +0000
Modify: 2018-03-19 16:33:38.223075036 +0000
Change: 2018-03-19 16:33:38.223075036 +0000
 Birth: -```

**Comment by cschneid** [comment]
As a comparison, on APM prod, with the same agent version (exact same rusage source), also on ubuntu 64 bit, the file size is a fair bit larger (134292 bytes vs the failing one having 67272 bytes).

```
$ file rusage.so
rusage.so: ELF 64-bit LSB  shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=6d221ca2a8795a7ab12c8e04e8889bcf5845f39d, not stripped
```

```
$ stat rusage.so
  File: ‘rusage.so’
  Size: 134292          Blocks: 264        IO Block: 4096   regular file
Device: ca01h/51713d    Inode: 4457654     Links: 1
Access: (0755/-rwxr-xr-x)  Uid: ( 1001/  deploy)   Gid: ( 1001/  deploy)
Access: 2018-03-29 16:31:30.478751505 +0000
Modify: 2018-02-27 18:22:16.262113289 +0000
Change: 2018-02-27 18:22:16.262113289 +0000
 Birth: -
```

**Comment by sixfeetover** [comment]
Update: We ended up nuking our entire application folder (`/home/ubuntu/apps/<the app>'` and re-deploying, which fixed it. Obviously a deeply dissatisfying fix since it doesn't reveal anything about the root cause, but on the plus side _seems_ to imply some weirdness on our machine rather than in the Scout code.

**Comment by cschneid** [comment]
Closing this, it appears to be a temporary glitch somewhere along the compilation path, rather than a code-related issue.

If anybody else sees this, please reopen the issue with whatever specifics you can provide.
