### ISSUE TITLE
Stackoverflow error

### ISSUE THREAD

**Issue by hashwin** [scoutapp/scout_apm_ruby#186]
The new version (2.4.10) seems to be causing some serious problems (possibly related to the gem **goldiloader**). It took down my site today with a stackoverflow error:

```
SystemStackError: stack level too deep
/app/vendor/bundle/ruby/2.5.0/gems/scout_apm-2.4.10/lib/scout_apm/request_manager.rb:12:in `find'
/app/vendor/bundle/ruby/2.5.0/gems/scout_apm-2.4.10/lib/scout_apm/request_manager.rb:7:in `lookup'
/app/vendor/bundle/ruby/2.5.0/gems/scout_apm-2.4.10/lib/scout_apm/instruments/active_record.rb:312:in `exec_queries_with_scout_instruments'
/app/vendor/bundle/ruby/2.5.0/gems/goldiloader-2.0.1/lib/goldiloader/active_record_patches.rb:35:in `exec_queries'
/app/vendor/bundle/ruby/2.5.0/gems/scout_apm-2.4.10/lib/scout_apm/instruments/active_record.rb:319:in `exec_queries_with_scout_instruments'
/app/vendor/bundle/ruby/2.5.0/gems/goldiloader-2.0.1/lib/goldiloader/active_record_patches.rb:35:in `exec_queries'
/app/vendor/bundle/ruby/2.5.0/gems/scout_apm-2.4.10/lib/scout_apm/instruments/active_record.rb:319:in `exec_queries_with_scout_instruments'
/app/vendor/bundle/ruby/2.5.0/gems/goldiloader-2.0.1/lib/goldiloader/active_record_patches.rb:35:in `exec_queries'
/app/vendor/bundle/ruby/2.5.0/gems/scout_apm-2.4.10/lib/scout_apm/instruments/active_record.rb:319:in `exec_queries_with_scout_instruments'
/app/vendor/bundle/ruby/2.5.0/gems/goldiloader-2.0.1/lib/goldiloader/active_record_patches.rb:35:in `exec_queries'
/app/vendor/bundle/ruby/2.5.0/gems/scout_apm-2.4.10/lib/scout_apm/instruments/active_record.rb:319:in `exec_queries_with_scout_instruments'
/app/vendor/bundle/ruby/2.5.0/gems/goldiloader-2.0.1/lib/goldiloader/active_record_patches.rb:35:in `exec_queries'
/app/vendor/bundle/ruby/2.5.0/gems/scout_apm-2.4.10/lib/scout_apm/instruments/active_record.rb:319:in `exec_queries_with_scout_instruments'
/app/vendor/bundle/ruby/2.5.0/gems/goldiloader-2.0.1/lib/goldiloader/active_record_patches.rb:35:in `exec_queries'
/app/vendor/bundle/ruby/2.5.0/gems/scout_apm-2.4.10/lib/scout_apm/instruments/active_record.rb:319:in `exec_queries_with_scout_instruments'
...
...
...
```

**Comment by cschneid** [comment]
@hashwin, this appears to be an issue like #114 - the goldiloader gem is instrumenting the same `exec_queries` method in AR as we (as of 2.4.10) are. But they modify it via `prepend`, and we use `alias_method`, and that causes a loop like you're seeing.

We have active work in #178 to fix this for good, but it's not quite landed. Temporarily, can you use 2.4.9 for a bit longer until we land the prepend changes. Alternately, this can sometimes be fixed by loading gems in a different order (by switching them in Gemfile).

**Comment by cschneid** [comment]
Just released version 2.4.11 which has exec_queries use Module#prepend if it's available. 

@hashwin Can you give it a try?

**Comment by hashwin** [comment]
@cschneid works now, thanks!

**Comment by jasdeepgosal** [comment]
Any idea when this fix will make it into the `v3.0.0.preXX` branch / next release? 

Thanks!

**Comment by cschneid** [comment]
@jasdeepgosal yes, next release. Let me see if anything else is waiting and get one out in the next day or so.

**Comment by cschneid** [comment]
@jasdeepgosal Oh, I just looked and it looks like this change is already released in `3.0.0.pre22`.

**Comment by jasdeepgosal** [comment]
Hm, peculiar, we got a very similar error on `3.0.0.pre22` so we ended up dropping down to `2.4.11` for now. 

```
SystemStackError: stack level too deep
/app/vendor/bundle/ruby/2.3.0/gems/scout_apm-3.0.0.pre22/lib/scout_apm/trace_compactor.rb:291:in `initialize'
/app/vendor/bundle/ruby/2.3.0/gems/scout_apm-3.0.0.pre22/lib/scout_apm/trace_compactor.rb:26:in `new'
/app/vendor/bundle/ruby/2.3.0/gems/scout_apm-3.0.0.pre22/lib/scout_apm/trace_compactor.rb:26:in `initialize'
/app/vendor/bundle/ruby/2.3.0/gems/scout_apm-3.0.0.pre22/lib/scout_apm/layer.rb:77:in `new'
/app/vendor/bundle/ruby/2.3.0/gems/scout_apm-3.0.0.pre22/lib/scout_apm/layer.rb:77:in `initialize'
/app/vendor/bundle/ruby/2.3.0/gems/scout_apm-3.0.0.pre22/lib/scout_apm/instruments/active_record.rb:313:in `new'
/app/vendor/bundle/ruby/2.3.0/gems/scout_apm-3.0.0.pre22/lib/scout_apm/instruments/active_record.rb:313:in `exec_queries_with_scout_instruments'
/app/vendor/bundle/ruby/2.3.0/gems/goldiloader-2.0.1/lib/goldiloader/active_record_patches.rb:35:in `exec_queries'
/app/vendor/bundle/ruby/2.3.0/gems/scout_apm-3.0.0.pre22/lib/scout_apm/instruments/active_record.rb:319:in `exec_queries_with_scout_instruments'
/app/vendor/bundle/ruby/2.3.0/gems/goldiloader-2.0.1/lib/goldiloader/active_record_patches.rb:35:in `exec_queries'
/app/vendor/bundle/ruby/2.3.0/gems/scout_apm-3.0.0.pre22/lib/scout_apm/instruments/active_record.rb:319:in `exec_queries_with_scout_instruments'
/app/vendor/bundle/ruby/2.3.0/gems/goldiloader-2.0.1/lib/goldiloader/active_record_patches.rb:35:in `exec_queries'
/app/vendor/bundle/ruby/2.3.0/gems/scout_apm-3.0.0.pre22/lib/scout_apm/instruments/active_record.rb:319:in `exec_queries_with_scout_instruments'
/app/vendor/bundle/ruby/2.3.0/gems/goldiloader-2.0.1/lib/goldiloader/active_record_patches.rb:35:in `exec_queries'
/app/vendor/bundle/ruby/2.3.0/gems/scout_apm-3.0.0.pre22/lib/scout_apm/instruments/active_record.rb:319:in `exec_queries_with_scout_instruments'
/app/vendor/bundle/ruby/2.3.0/gems/goldiloader-2.0.1/lib/goldiloader/active_record_patches.rb:35:in `exec_queries'
/app/vendor/bundle/ruby/2.3.0/gems/scout_apm-3.0.0.pre22/lib/scout_apm/instruments/active_record.rb:319:in `exec_queries_with_scout_instruments'
/app/vendor/bundle/ruby/2.3.0/gems/goldiloader-2.0.1/lib/goldiloader/active_record_patches.rb:35:in `exec_queries'
/app/vendor/bundle/ruby/2.3.0/gems/scout_apm-3.0.0.pre22/lib/scout_apm/instruments/active_record.rb:319:in `exec_queries_with_scout_instruments'
/app/vendor/bundle/ruby/2.3.0/gems/goldiloader-2.0.1/lib/goldiloader/active_record_patches.rb:35:in `exec_queries'
/app/vendor/bundle/ruby/2.3.0/gems/scout_apm-3.0.0.pre22/lib/scout_apm/instruments/active_record.rb:319:in `exec_queries_with_scout_instruments'
/app/vendor/bundle/ruby/2.3.0/gems/goldiloader-2.0.1/lib/goldiloader/active_record_patches.rb:35:in `exec_queries'
/app/vendor/bundle/ruby/2.3.0/gems/scout_apm-3.0.0.pre22/lib/scout_apm/instruments/active_record.rb:319:in `exec_queries_with_scout_instruments'
/app/vendor/bundle/ruby/2.3.0/gems/goldiloader-2.0.1/lib/goldiloader/active_record_patches.rb:35:in `exec_queries'
/app/vendor/bundle/ruby/2.3.0/gems/scout_apm-3.0.0.pre22/lib/scout_apm/instruments/active_record.rb:319:in `exec_queries_with_scout_instruments'
/app/vendor/bundle/ruby/2.3.0/gems/goldiloader-2.0.1/lib/goldiloader/active_record_patches.rb:35:in `exec_queries'
…
```

LMK if I should open a new ticket?

**Comment by cschneid** [comment]
Yeah, lets open a new ticket for this one - can you copy that trace, and also the version of gems & ruby you have installed? We'll take a look.
