### ISSUE TITLE
[detailed-traces] Error merging reporting periods undefined method `web_traces'

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/scout_apm_ruby#239]
When running the latest `scoutprof-detailed-traces` branch, I see the following error in the log. No data is reported. I've tried deleted the local `scout_apm.db` file as well.

```
[12/13/18 15:18:12 -0700 dlite.local (69619)] DEBUG : Error merging reporting periods undefined method `web_traces' for #<ScoutApm::StoreReportingPeriod:0x00007fbb43991550>
Did you mean?  job_traces
[12/13/18 15:18:12 -0700 dlite.local (69619)] DEBUG : Error merging reporting periods ["/Users/dlite/.rvm/gems/ruby-2.4.5/bundler/gems/scout_apm_ruby-092693762de3/lib/scout_apm/store.rb:249:in `merge'", "/Users/dlite/.rvm/gems/ruby-2.4.5/bundler/gems/scout_apm_ruby-092693762de3/lib/scout_apm/reporting.rb:49:in `block (2 levels) in report_to_server'", "/Users/dlite/.rvm/gems/ruby-2.4.5/bundler/gems/scout_apm_ruby-092693762de3/lib/scout_apm/reporting.rb:49:in `each'", "/Users/dlite/.rvm/gems/ruby-2.4.5/bundler/gems/scout_apm_ruby-092693762de3/lib/scout_apm/reporting.rb:49:in `inject'", "/Users/dlite/.rvm/gems/ruby-2.4.5/bundler/gems/scout_apm_ruby-092693762de3/lib/scout_apm/reporting.rb:49:in `block in report_to_server'", "/Users/dlite/.rvm/gems/ruby-2.4.5/bundler/gems/scout_apm_ruby-092693762de3/lib/scout_apm/layaway.rb:103:in `with_claim'", "/Users/dlite/.rvm/gems/ruby-2.4.5/bundler/gems/scout_apm_ruby-092693762de3/lib/scout_apm/reporting.rb:45:in `report_to_server'", "/Users/dlite/.rvm/gems/ruby-2.4.5/bundler/gems/scout_apm_ruby-092693762de3/lib/scout_apm/reporting.rb:36:in `process_metrics'", "/Users/dlite/.rvm/gems/ruby-2.4.5/bundler/gems/scout_apm_ruby-092693762de3/lib/scout_apm/periodic_work.rb:13:in `run'", "/Users/dlite/.rvm/gems/ruby-2.4.5/bundler/gems/scout_apm_ruby-092693762de3/lib/scout_apm/agent.rb:182:in `block (2 levels) in start_background_worker'", "/Users/dlite/.rvm/gems/ruby-2.4.5/bundler/gems/scout_apm_ruby-092693762de3/lib/scout_apm/background_worker.rb:61:in `block in start'", "/Users/dlite/.rvm/gems/ruby-2.4.5/bundler/gems/scout_apm_ruby-092693762de3/lib/scout_apm/background_worker.rb:44:in `loop'", "/Users/dlite/.rvm/gems/ruby-2.4.5/bundler/gems/scout_apm_ruby-092693762de3/lib/scout_apm/background_worker.rb:44:in `start'", "/Users/dlite/.rvm/gems/ruby-2.4.5/bundler/gems/scout_apm_ruby-092693762de3/lib/scout_apm/agent.rb:181:in `block in start_background_worker'"]
```

**Comment by cschneid** [comment]
Sorry about that, I had fixed, but not pushed the fix for that.

**Comment by itsderek23** [comment]
Works! Thanks!

![image](https://user-images.githubusercontent.com/7880/50011005-23685a80-ff78-11e8-926e-12b4ddcfa992.png)
