### ISSUE TITLE
Uninitialized constant ScoutApm::AutoInstrument....Parser

### ISSUE THREAD

**Issue by ioquatix** [scoutapp/scout_apm_ruby#250]
Failing in `load_iseq` after running `rake`.

**Comment by ioquatix** [comment]
cc @geesu

**Comment by ioquatix** [comment]
Just adding the error report for reference.

![unnamed](https://user-images.githubusercontent.com/30030/54352219-04cc4980-46b6-11e9-9e76-f206ecd2ca5f.png)

**Comment by ioquatix** [comment]
Can you please show me the full contents of your `Gemfile`, `Gemfile.lock`, `boot.rb`. If this needs to remain private please DM me on Slack.

For the record: I tried installing identical versions of all the gems I could see from the screenshots but could not reproduce the issue.

**Comment by ioquatix** [comment]
@Geesu do you mind trying the latest branch here `auto_instrument`. I've changed the load order which should make it impossible for the files to fail in the way indicated by your backtrace.

Additionally, if you try it and it fails, can you give me a full backtrace?

**Comment by Geesu** [comment]
```#!/bin/bash -eo pipefail
RAILS_ENV=test bundle exec rake db:structure:load
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.0-compliant syntax, but you are running 2.6.1.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
rake aborted!
NameError: uninitialized constant ScoutApm::AutoInstrument::Rails::Parser
/home/circleci/flowspace/vendor/bundle/bundler/gems/scout_apm_ruby-bc460a371b3a/lib/scout_apm/auto_instrument/rails.rb:23:in `rewrite'
/home/circleci/flowspace/vendor/bundle/bundler/gems/scout_apm_ruby-bc460a371b3a/lib/scout_apm/auto_instrument/instruction_sequence.rb:11:in `load_iseq'
/home/circleci/flowspace/vendor/bundle/gems/activesupport-5.1.6.1/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
/home/circleci/flowspace/vendor/bundle/gems/activesupport-5.1.6.1/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
/home/circleci/flowspace/vendor/bundle/gems/activesupport-5.1.6.1/lib/active_support/dependencies/interlock.rb:11:in `loading'
/home/circleci/flowspace/vendor/bundle/gems/inherited_resources-1.9.0/app/controllers/inherited_resources/base.rb:11:in `<module:InheritedResources>'
/home/circleci/flowspace/vendor/bundle/gems/inherited_resources-1.9.0/app/controllers/inherited_resources/base.rb:1:in `<main>'
/home/circleci/flowspace/vendor/bundle/gems/activesupport-5.1.6.1/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
/home/circleci/flowspace/vendor/bundle/gems/activesupport-5.1.6.1/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
/home/circleci/flowspace/vendor/bundle/gems/activesupport-5.1.6.1/lib/active_support/dependencies/interlock.rb:11:in `loading'
/home/circleci/flowspace/vendor/bundle/bundler/gems/activeadmin-d95a9a853fd4/lib/active_admin/base_controller/authorization.rb:2:in `<module:ActiveAdmin>'
/home/circleci/flowspace/vendor/bundle/bundler/gems/activeadmin-d95a9a853fd4/lib/active_admin/base_controller/authorization.rb:1:in `<main>'
/home/circleci/flowspace/vendor/bundle/bundler/gems/activeadmin-d95a9a853fd4/lib/active_admin/base_controller.rb:1:in `<main>'
/home/circleci/flowspace/vendor/bundle/bundler/gems/activeadmin-d95a9a853fd4/lib/active_admin/resource_controller/action_builder.rb:2:in `<module:ActiveAdmin>'
/home/circleci/flowspace/vendor/bundle/bundler/gems/activeadmin-d95a9a853fd4/lib/active_admin/resource_controller/action_builder.rb:1:in `<main>'
/home/circleci/flowspace/vendor/bundle/bundler/gems/activeadmin-d95a9a853fd4/lib/active_admin/resource_controller.rb:1:in `<main>'
/home/circleci/flowspace/vendor/bundle/bundler/gems/activeadmin-d95a9a853fd4/lib/active_admin/batch_actions.rb:7:in `block in <main>'
/home/circleci/flowspace/vendor/bundle/bundler/gems/activeadmin-d95a9a853fd4/lib/active_admin.rb:116:in `block in wrap_block_for_active_support_notifications'
/home/circleci/flowspace/vendor/bundle/gems/activesupport-5.1.6.1/lib/active_support/notifications/fanout.rb:116:in `publish'
/home/circleci/flowspace/vendor/bundle/gems/activesupport-5.1.6.1/lib/active_support/notifications/fanout.rb:50:in `block in publish'
/home/circleci/flowspace/vendor/bundle/gems/activesupport-5.1.6.1/lib/active_support/notifications/fanout.rb:50:in `each'
/home/circleci/flowspace/vendor/bundle/gems/activesupport-5.1.6.1/lib/active_support/notifications/fanout.rb:50:in `publish'
/home/circleci/flowspace/vendor/bundle/gems/activesupport-5.1.6.1/lib/active_support/notifications.rb:161:in `publish'
/home/circleci/flowspace/vendor/bundle/bundler/gems/activeadmin-d95a9a853fd4/lib/active_admin/application.rb:115:in `load!'
/home/circleci/flowspace/vendor/bundle/bundler/gems/activeadmin-d95a9a853fd4/lib/active_admin/application.rb:142:in `routes'
/home/circleci/flowspace/vendor/bundle/bundler/gems/activeadmin-d95a9a853fd4/lib/active_admin.rb:76:in `routes'
/home/circleci/flowspace/config/routes.rb:19:in `block (2 levels) in <main>'
/home/circleci/flowspace/vendor/bundle/gems/devise-4.6.1/lib/devise/rails/routes.rb:292:in `block in authenticate'
/home/circleci/flowspace/vendor/bundle/gems/devise-4.6.1/lib/devise/rails/routes.rb:484:in `block in constraints_for'
/home/circleci/flowspace/vendor/bundle/gems/actionpack-5.1.6.1/lib/action_dispatch/routing/mapper.rb:996:in `block in constraints'
/home/circleci/flowspace/vendor/bundle/gems/actionpack-5.1.6.1/lib/action_dispatch/routing/mapper.rb:867:in `scope'
/home/circleci/flowspace/vendor/bundle/gems/actionpack-5.1.6.1/lib/action_dispatch/routing/mapper.rb:996:in `constraints'
/home/circleci/flowspace/vendor/bundle/gems/devise-4.6.1/lib/devise/rails/routes.rb:483:in `constraints_for'
/home/circleci/flowspace/vendor/bundle/gems/devise-4.6.1/lib/devise/rails/routes.rb:291:in `authenticate'
/home/circleci/flowspace/config/routes.rb:14:in `block in <main>'
/home/circleci/flowspace/vendor/bundle/gems/actionpack-5.1.6.1/lib/action_dispatch/routing/route_set.rb:436:in `instance_exec'
/home/circleci/flowspace/vendor/bundle/gems/actionpack-5.1.6.1/lib/action_dispatch/routing/route_set.rb:436:in `eval_block'
/home/circleci/flowspace/vendor/bundle/gems/actionpack-5.1.6.1/lib/action_dispatch/routing/route_set.rb:418:in `draw'
/home/circleci/flowspace/config/routes.rb:6:in `<main>'
/home/circleci/flowspace/vendor/bundle/gems/railties-5.1.6.1/lib/rails/application/routes_reloader.rb:55:in `block in load_paths'
/home/circleci/flowspace/vendor/bundle/gems/railties-5.1.6.1/lib/rails/application/routes_reloader.rb:55:in `each'
/home/circleci/flowspace/vendor/bundle/gems/railties-5.1.6.1/lib/rails/application/routes_reloader.rb:55:in `load_paths'
/home/circleci/flowspace/vendor/bundle/gems/railties-5.1.6.1/lib/rails/application/routes_reloader.rb:18:in `reload!'
/home/circleci/flowspace/vendor/bundle/gems/railties-5.1.6.1/lib/rails/application/routes_reloader.rb:41:in `block in updater'
/home/circleci/flowspace/vendor/bundle/gems/activesupport-5.1.6.1/lib/active_support/file_update_checker.rb:81:in `execute'
/home/circleci/flowspace/vendor/bundle/gems/railties-5.1.6.1/lib/rails/application/routes_reloader.rb:42:in `updater'
/home/circleci/flowspace/vendor/bundle/gems/railties-5.1.6.1/lib/rails/application/routes_reloader.rb:31:in `execute_if_updated'
/home/circleci/flowspace/vendor/bundle/gems/railties-5.1.6.1/lib/rails/application/finisher.rb:128:in `block in <module:Finisher>'
/home/circleci/flowspace/vendor/bundle/gems/railties-5.1.6.1/lib/rails/initializable.rb:30:in `instance_exec'
/home/circleci/flowspace/vendor/bundle/gems/railties-5.1.6.1/lib/rails/initializable.rb:30:in `run'
/home/circleci/flowspace/vendor/bundle/gems/railties-5.1.6.1/lib/rails/initializable.rb:59:in `block in run_initializers'
/home/circleci/flowspace/vendor/bundle/gems/railties-5.1.6.1/lib/rails/initializable.rb:58:in `run_initializers'
/home/circleci/flowspace/vendor/bundle/gems/railties-5.1.6.1/lib/rails/application.rb:353:in `initialize!'
/home/circleci/flowspace/config/environment.rb:5:in `<main>'
/home/circleci/flowspace/vendor/bundle/gems/railties-5.1.6.1/lib/rails/application.rb:329:in `require_environment!'
/home/circleci/flowspace/vendor/bundle/gems/railties-5.1.6.1/lib/rails/application.rb:445:in `block in run_tasks_blocks'
/home/circleci/flowspace/vendor/bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => db:structure:load => environment
(See full trace by running task with --trace)
Exited with code 1```

Still fails :(

**Comment by Geesu** [comment]
Our Gemfile:

```
# Performance monitoring
gem 'scout_apm', git: 'https://github.com/scoutapp/scout_apm_ruby.git', branch: 'auto_instruments'
# Required by the auto_instruments branch of scout_apm
gem 'parser'
```

**Comment by ioquatix** [comment]
I've changed `rescue SyntaxError` to `rescue` which should catch this error.

I've also changed `Parser` to `::Parser` which is consistent with other usage.

Do you mind trying again?

I think you will probably get a warning.

**Comment by dlanderson** [comment]
This looks resolved. Closing

**Comment by ioquatix** [comment]
@dlanderson did you talk to @Geesu ?
