### ISSUE TITLE
RuntimeError: st_table too big in request_histograms_by_time

### ISSUE THREAD

**Issue by yihyang** [scoutapp/scout_apm_ruby#252]
```
message='#<RuntimeError: st_table too big>' #<RuntimeError: st_table too big>
message="/usr/local/bundle/gems/scout_apm-3.0.0.pre23/lib/scout_apm/agent_context.rb:114:in `block in request_histograms_by_time'" /usr/local/bundle/gems/scout_apm-3.0.0.pre23/lib/scout_apm/agent_context.rb:114:in `block in request_histograms_by_time'
message="/usr/local/bundle/gems/scout_apm-3.0.0.pre23/lib/scout_apm/layer_converters/histograms.rb:8:in `record!'" /usr/local/bundle/gems/scout_apm-3.0.0.pre23/lib/scout_apm/layer_converters/histograms.rb:8:in `record!'
message="/usr/local/bundle/gems/scout_apm-3.0.0.pre23/lib/scout_apm/tracked_request.rb:326:in `block in record!'" /usr/local/bundle/gems/scout_apm-3.0.0.pre23/lib/scout_apm/tracked_request.rb:326:in `block in record!'
message="/usr/local/bundle/gems/scout_apm-3.0.0.pre23/lib/scout_apm/tracked_request.rb:325:in `each'" /usr/local/bundle/gems/scout_apm-3.0.0.pre23/lib/scout_apm/tracked_request.rb:325:in `each'
message="/usr/local/bundle/gems/scout_apm-3.0.0.pre23/lib/scout_apm/tracked_request.rb:325:in `inject'" /usr/local/bundle/gems/scout_apm-3.0.0.pre23/lib/scout_apm/tracked_request.rb:325:in `inject'
message="/usr/local/bundle/gems/scout_apm-3.0.0.pre23/lib/scout_apm/tracked_request.rb:325:in `record!'" /usr/local/bundle/gems/scout_apm-3.0.0.pre23/lib/scout_apm/tracked_request.rb:325:in `record!'
message="/usr/local/bundle/gems/scout_apm-3.0.0.pre23/lib/scout_apm/synchronous_recorder.rb:27:in `record!'" /usr/local/bundle/gems/scout_apm-3.0.0.pre23/lib/scout_apm/synchronous_recorder.rb:27:in `record!'
message="/usr/local/bundle/gems/scout_apm-3.0.0.pre23/lib/scout_apm/tracked_request.rb:229:in `stop_request'" /usr/local/bundle/gems/scout_apm-3.0.0.pre23/lib/scout_apm/tracked_request.rb:229:in `stop_request'
message="/usr/local/bundle/gems/scout_apm-3.0.0.pre23/lib/scout_apm/tracked_request.rb:123:in `stop_layer'" /usr/local/bundle/gems/scout_apm-3.0.0.pre23/lib/scout_apm/tracked_request.rb:123:in `stop_layer'
message="/usr/local/bundle/gems/scout_apm-3.0.0.pre23/lib/scout_apm/instruments/middleware_summary.rb:60:in `call'" /usr/local/bundle/gems/scout_apm-3.0.0.pre23/lib/scout_apm/instruments/middleware_summary.rb:60:in `call'
message="/usr/local/bundle/gems/railties-5.1.6/lib/rails/engine.rb:522:in `call'" /usr/local/bundle/gems/railties-5.1.6/lib/rails/engine.rb:522:in `call'
message="/usr/local/bundle/gems/puma-3.11.4/lib/puma/configuration.rb:225:in `call'" /usr/local/bundle/gems/puma-3.11.4/lib/puma/configuration.rb:225:in `call'
message="/usr/local/bundle/gems/puma-3.11.4/lib/puma/server.rb:632:in `handle_request'" /usr/local/bundle/gems/puma-3.11.4/lib/puma/server.rb:632:in `handle_request'
message="/usr/local/bundle/gems/puma-3.11.4/lib/puma/server.rb:446:in `process_client'" /usr/local/bundle/gems/puma-3.11.4/lib/puma/server.rb:446:in `process_client'
message="/usr/local/bundle/gems/puma-3.11.4/lib/puma/server.rb:306:in `block in run'" /usr/local/bundle/gems/puma-3.11.4/lib/puma/server.rb:306:in `block in run'
message="/usr/local/bundle/gems/puma-3.11.4/lib/puma/thread_pool.rb:120:in `block in spawn_thread'" /usr/local/bundle/gems/puma-3.11.4/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

Hi there, my team faced the above message which caused the application to fail. 

Did some research into ruby source code and found the following:

https://github.com/ruby/ruby/blob/ab2547d786572f4c14e0d849f5f64f006425c5ba/st.c#L355

```
#ifndef NOT_RUBY
    /* Ran out of the table entries */
    rb_raise(rb_eRuntimeError, "st_table too big");
#endif
```

I suspected that the histograms that was being fetched by the gem was too large and therefore causes memory to run out of table entries. Would like to know whether anyone faced similar issue with this? If so, is there any solution to this?

**Comment by cschneid** [comment]
I have never seen that error before.

A few initial questions:
* Has this happened more than once? Is there a way to reproduce it so I can look into it more?
* Do you have any custom instrumentation in your application?

**Comment by cschneid** [comment]
* What version of Ruby, and is it custom compiled in any way, or a system packaged version?

**Comment by kamilbednarz** [comment]
Hey, just experienced the same problem. I saw this only on one of the web servers in the cluster, after 1 day of rather quiet uptime. 


after upgrading rack from 2.0.7 to 2.2.2. 
Every 

scout_apm 2.6.4
rack 2.2.2
Amazon Linux 2.11.8
