### ISSUE TITLE
Usage of rescue_from in `application_controller.rb` causes the instrumentation to crash

### ISSUE THREAD

**Issue by ioquatix** [scoutapp/scout_apm_ruby#254]
```ruby
 rescue_from Exception do |e|
    if e.is_a? Pundit::NotAuthorizedError
      unauthorized_error
    elsif e.is_a? ActionController::ParameterMissing
      error(status: 422, message: e.message)
    else
      log_error(e)
      error message: 'Internal error', exception: e
    end
  end
```

(note: `unathorized_error`, `error` and `log_error` are methods in ApplicationController)

This is an example of an error that occurs:

```ruby
NoMethodError:
  undefined method `children' for nil:NilClass

/home/jon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/scout_apm_ruby-d45a07a62448/lib/scout_apm/auto_instrument/rails.rb:50:in `instrument'
/home/jon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/scout_apm_ruby-d45a07a62448/lib/scout_apm/auto_instrument/rails.rb:65:in `on_block'
ast (2.4.0) lib/ast/processor/mixin.rb:259:in `process'
/home/jon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/scout_apm_ruby-d45a07a62448/lib/scout_apm/auto_instrument/rails.rb:114:in `process'
ast (2.4.0) lib/ast/processor/mixin.rb:276:in `block in process_all'
ast (2.4.0) lib/ast/processor/mixin.rb:275:in `map'
ast (2.4.0) lib/ast/processor/mixin.rb:275:in `process_all'
parser (2.6.0.0) lib/parser/ast/processor.rb:11:in `process_regular_node'
ast (2.4.0) lib/ast/processor/mixin.rb:259:in `process'
/home/jon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/scout_apm_ruby-d45a07a62448/lib/scout_apm/auto_instrument/rails.rb:114:in `process'
ast (2.4.0) lib/ast/processor/mixin.rb:276:in `block in process_all'
ast (2.4.0) lib/ast/processor/mixin.rb:275:in `map'
ast (2.4.0) lib/ast/processor/mixin.rb:275:in `process_all'
parser (2.6.0.0) lib/parser/ast/processor.rb:11:in `process_regular_node'
ast (2.4.0) lib/ast/processor/mixin.rb:259:in `process'
/home/jon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/scout_apm_ruby-d45a07a62448/lib/scout_apm/auto_instrument/rails.rb:114:in `process'
parser (2.6.0.0) lib/parser/tree_rewriter.rb:67:in `rewrite'
/home/jon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/scout_apm_ruby-d45a07a62448/lib/scout_apm/auto_instrument/rails.rb:30:in `rewrite'
/home/jon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/scout_apm_ruby-d45a07a62448/lib/scout_apm/auto_instrument/instruction_sequence.rb:11:in `load_iseq'
activesupport (5.2.2) lib/active_support/dependencies.rb:476:in `load'
activesupport (5.2.2) lib/active_support/dependencies.rb:476:in `block in load_file'
activesupport (5.2.2) lib/active_support/dependencies.rb:661:in `new_constants_in'
activesupport (5.2.2) lib/active_support/dependencies.rb:475:in `load_file'
activesupport (5.2.2) lib/active_support/dependencies.rb:373:in `block in require_or_load'
activesupport (5.2.2) lib/active_support/dependencies.rb:37:in `block in load_interlock'
activesupport (5.2.2) lib/active_support/dependencies/interlock.rb:14:in `block in loading'
activesupport (5.2.2) lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
activesupport (5.2.2) lib/active_support/dependencies/interlock.rb:13:in `loading'
activesupport (5.2.2) lib/active_support/dependencies.rb:37:in `load_interlock'
activesupport (5.2.2) lib/active_support/dependencies.rb:356:in `require_or_load'
activesupport (5.2.2) lib/active_support/dependencies.rb:510:in `load_missing_constant'
activesupport (5.2.2) lib/active_support/dependencies.rb:195:in `const_missing'
my_controller.rb:4:in `<compiled>'
```

cc @jonekdahl

**Comment by ioquatix** [comment]
I apologise on the turn around time for this issue. However, the above commit should fix the problem. Please do let me know if you run into any other issues.

Hopefully, @dlanderson is happy with the change and can merge it into `auto_instrument_beta` branch.

**Comment by ioquatix** [comment]
@dlanderson Everything is passing but RuboCop is complaining about our test sample code: https://travis-ci.org/scoutapp/scout_apm_ruby/jobs/506224745

Can we ignore everything in that directory?

**Comment by jonekdahl** [comment]
@ioquatix Thanks, the fix works for me.
