### ISSUE TITLE
scout_apm 2.5.0 raise error in development

### ISSUE THREAD

**Issue by PikachuEXE** [scoutapp/scout_apm_ruby#267]
[`LimitedLayer`](https://github.com/scoutapp/scout_apm_ruby/blob/master/lib/scout_apm/limited_layer.rb) seems to be lacking some methods called by [LayerConverters::TraceConverter#create_spans](
https://github.com/scoutapp/scout_apm_ruby/blob/master/lib/scout_apm/layer_converters/trace_converter.rb#L89-L90)

#### Stacktrace
```
Exception NoMethodError in Rack application object (undefined method `start_time' for #<ScoutApm::LimitedLayer:0x00007fee1b3b1b20>) (process 35747, thread 0x00007fedfd062f78(Worker 1)):
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_converters/trace_converter.rb:89:in `create_spans'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_converters/trace_converter.rb:121:in `block in create_spans'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:67:in `block in each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:66:in `each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:66:in `each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_converters/trace_converter.rb:119:in `create_spans'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_converters/trace_converter.rb:121:in `block in create_spans'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:61:in `block (2 levels) in each'
from /Users/pikachuexe/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/set.rb:338:in `each_key'
from /Users/pikachuexe/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/set.rb:338:in `each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:60:in `block in each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:59:in `each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:59:in `each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_converters/trace_converter.rb:119:in `create_spans'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_converters/trace_converter.rb:121:in `block in create_spans'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:61:in `block (2 levels) in each'
from /Users/pikachuexe/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/set.rb:338:in `each_key'
from /Users/pikachuexe/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/set.rb:338:in `each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:60:in `block in each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:59:in `each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:59:in `each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_converters/trace_converter.rb:119:in `create_spans'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_converters/trace_converter.rb:121:in `block in create_spans'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:61:in `block (2 levels) in each'
from /Users/pikachuexe/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/set.rb:338:in `each_key'
from /Users/pikachuexe/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/set.rb:338:in `each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:60:in `block in each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:59:in `each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_children_set.rb:59:in `each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_converters/trace_converter.rb:119:in `create_spans'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_converters/trace_converter.rb:60:in `call'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_converters/slow_request_converter.rb:95:in `span_trace'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_converters/slow_request_converter.rb:56:in `call'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/scored_item_set.rb:81:in `store!'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/scored_item_set.rb:62:in `<<'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/store.rb:259:in `block in merge_slow_transactions!'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/store.rb:258:in `each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/store.rb:258:in `merge_slow_transactions!'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/store.rb:66:in `block in track_slow_transaction!'
from /Users/pikachuexe/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/store.rb:65:in `track_slow_transaction!'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/layer_converters/slow_request_converter.rb:13:in `record!'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/tracked_request.rb:312:in `block in record!'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/tracked_request.rb:311:in `each'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/tracked_request.rb:311:in `inject'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/tracked_request.rb:311:in `record!'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/synchronous_recorder.rb:27:in `record!'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/tracked_request.rb:216:in `stop_request'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/tracked_request.rb:124:in `stop_layer'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/scout_apm-2.5.0/lib/scout_apm/instruments/middleware_summary.rb:60:in `call'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/railties-5.2.3/lib/rails/engine.rb:524:in `call'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
from /Users/pikachuexe/.rvm/gems/ruby-2.6.3/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by metade** [comment]
I'm getting similar errors in production!

**Comment by cschneid** [comment]
Thank you for the report, sorry for the issue! We'll have this fixed up ASAP, but I would recommend downgrading back to 2.4.24 on production until we can get that out.

**Comment by itsderek23** [comment]
@PikachuEXE @metade - mind trying version `2.5.1`? Let us know if you hit this exception. 

Sorry for the issues and thanks a lot for reporting!

/cc @cschneid

**Comment by PikachuEXE** [comment]
I confirm the issue is fixed 
(tested in development since the error can only be reproduced in development for me)

**Comment by metade** [comment]
Looks like it's fixed for us on production too.

Thanks!

**Comment by itsderek23** [comment]
Thanks all for the updates. Again, apologies for the issues.
