### ISSUE TITLE
Syntax error after installing gem from auto_instruments branch

### ISSUE THREAD

**Issue by tchukuchuk** [scoutapp/scout_apm_ruby#281]
Hi,

I have just installed the 0ba159eab401d0a515cde32303c7984479312a1c revision on the branch auto_instruments and I have this error :

```
FATAL -- : base_controller.rb:107: syntax error, unexpected '=', expecting '.' or &. or :: or '['
...llection'"]){self.collection} = ::ScoutApm::AutoInstrument("...
...                              ^
/usr/local/bundle/bundler/gems/scout_apm_ruby-0ba159eab401/lib/scout_apm/auto_instrument/instruction_sequence.rb:11:in `compile'
/usr/local/bundle/bundler/gems/scout_apm_ruby-0ba159eab401/lib/scout_apm/auto_instrument/instruction_sequence.rb:11:in `load_iseq'
bootsnap (1.4.2) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
bootsnap (1.4.2) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
activesupport (5.2.3) lib/active_support/dependencies.rb:476:in `block in load_file'
activesupport (5.2.3) lib/active_support/dependencies.rb:661:in `new_constants_in'
activesupport (5.2.3) lib/active_support/dependencies.rb:475:in `load_file'
activesupport (5.2.3) lib/active_support/dependencies.rb:373:in `block in require_or_load'
activesupport (5.2.3) lib/active_support/dependencies.rb:37:in `block in load_interlock'
activesupport (5.2.3) lib/active_support/dependencies/interlock.rb:14:in `block in loading'
activesupport (5.2.3) lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
activesupport (5.2.3) lib/active_support/dependencies/interlock.rb:13:in `loading'
activesupport (5.2.3) lib/active_support/dependencies.rb:37:in `load_interlock'
activesupport (5.2.3) lib/active_support/dependencies.rb:356:in `require_or_load'
bootsnap (1.4.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:48:in `block in require_or_load'
bootsnap (1.4.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
bootsnap (1.4.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:47:in `require_or_load'
activesupport (5.2.3) lib/active_support/dependencies.rb:510:in `load_missing_constant'
bootsnap (1.4.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `block in load_missing_constant'
bootsnap (1.4.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
bootsnap (1.4.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
activesupport (5.2.3) lib/active_support/dependencies.rb:195:in `const_missing'
```

Regards,

Julien

**Comment by ioquatix** [comment]
@tchukuchuk can you give me a few lines of context either side of the error?

**Comment by tchukuchuk** [comment]
@ioquatix : I have extracted my code here :

https://gist.github.com/tchukuchuk/8e3847d66001e29a6e622bdb72bdf547

**Comment by ioquatix** [comment]
Thanks, that was super helpful and I've added a test, and fixed the issue in the PR/branch.

**Comment by dlanderson** [comment]
@tchukuchuk thanks for the report and the info. This is fixed in https://github.com/scoutapp/scout_apm_ruby/commit/24691d5563b8939eb4d8260cbc945136279bbcc3
