### ISSUE TITLE
Avoid starting threads in the parent process of forking servers

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout_apm_ruby#325]
A customer reports that Puma is emitting a warning during start that the background thread is being started and won't survive a fork.

This does not affect the behavior of Scout, as the thread will be restarted in the forked child process, but it is a scary looking warning that we should avoid.

```
12:21:16 PM web.1 |  [16321] ! WARNING: Detected 2 Thread(s) started in app boot:
12:21:16 PM web.1 |  [16321] ! #<Thread:0x00007fae721b32d0@/Users/.../.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/scout_apm-2.6.6/lib/scout_apm/agent.rb:174 sleep> - /Users/.../.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/scout_apm-2.6.6/lib/scout_apm/background_worker.rb:51:in `sleep'
```

**Comment by dlanderson** [comment]
I can't reproduce with the latest `scout_apm_ruby` version 5.0.0. Please reopen if someone hits this again.

**Comment by bf4** [comment]
fwiw, been seeing this for a while, currently on Ruby 2.7.6, scout_apm-5.1.1, 6.1.4.4

running on Heroku

```
2022-04-20T03:52:01.339485+00:00 app[web.2]: [3] * Listening on http://0.0.0.0:23787
2022-04-20T03:52:01.339526+00:00 app[web.2]: [3] ! WARNING: Detected 2 Thread(s) started in app boot:
2022-04-20T03:52:01.339564+00:00 app[web.2]: [3] ! #<Thread:0x00007ff9c2165148 /app/vendor/bundle/ruby/2.7.0/gems/scout_apm-5.1.1/lib/scout_apm/agent.rb:176 sleep> - /app/vendor/bundle/ruby/2.7.0/gems/scout_apm-5.1.1/lib/scout_apm/background_worker.rb:51:in `sleep'
2022-04-20T03:52:01.339587+00:00 app[web.2]: [3] ! #<Thread:0x00007ff9bfac0ee8 /app/vendor/bundle/ruby/2.7.0/gems/scout_apm-5.1.1/lib/scout_apm/agent.rb:210 sleep> - /app/vendor/bundle/ruby/2.7.0/gems/scout_apm-5.1.1/lib/scout_apm/background_worker.rb:51:in `sleep'
```
