### ISSUE TITLE
Autoinstruments will error when controller has a hanging method

### ISSUE THREAD

**Issue by jrothrock** [scoutapp/scout_apm_ruby#386]
Minimal failing test:
```
class TestController < ApplicationController
end
def hanging_method
   Test.first
end
```
Backtrace:
```
NoMethodError: undefined method `children' for nil:NilClass
    /Users/jackrothrock/scout_apm_ruby/lib/scout_apm/auto_instrument/rails.rb:73:in `instrument'
    /Users/jackrothrock/scout_apm_ruby/lib/scout_apm/auto_instrument/rails.rb:137:in `on_send'
```

**Comment by cschneid** [comment]
Fixed in 8d1e330
