### ISSUE TITLE
Exception: undefined method `record_stop_time!' for nil:NilClass

### ISSUE THREAD

**Issue by swapnilabnave** [scoutapp/scout_apm_ruby#46]
* ruby 2.1.8p440 (2015-12-16 revision 53160) [x86_64-linux-gnu]
* rails 3.2.22.1
* scout_apm (2.0.0.pre)

```
App 6038 stderr: [ 2016-05-31 22:07:27.8294 6166/0x000000038fc048(Worker 12) utils.rb:71 ]: *** Exception NoMethodError in Rack application object (undefined method `record_stop_time!' for nil:NilClass) (process 6166, thread 0x000000038fc048(Worker 12)):
[ 2016-05-31 22:07:27.8295 6001/7f8d0bfff700 age/Cor/Con/InternalUtils.cpp:96 ]: [Client 3-36] Sending 502 response: application did not send a complete response
App 6038 stderr: 	from /var/www/sg/vendor/cache/ruby/2.1.0/gems/scout_apm-2.0.0.pre/lib/scout_apm/tracked_request.rb:70:in `stop_layer'
App 6038 stderr: 	from /var/www/sg/vendor/cache/ruby/2.1.0/gems/scout_apm-2.0.0.pre/lib/scout_apm/instruments/middleware_summary.rb:46:in `call'
App 6038 stderr: 	from /var/www/sg/vendor/cache/ruby/2.1.0/gems/railties-3.2.22.1/lib/rails/engine.rb:484:in `call'
App 6038 stderr: 	from /var/www/sg/vendor/cache/ruby/2.1.0/gems/railties-3.2.22.1/lib/rails/application.rb:231:in `call'
App 6038 stderr: 	from /var/www/sg/vendor/cache/ruby/2.1.0/gems/railties-3.2.22.1/lib/rails/railtie/configurable.rb:30:in `method_missing'
App 6038 stderr: 	from /var/www/sg/vendor/cache/ruby/2.1.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
App 6038 stderr: 	from /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:81:in `process_request'
App 6038 stderr: 	from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:137:in `accept_and_process_next_request'
App 6038 stderr: 	from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:98:in `main_loop'
App 6038 stderr: 	from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:440:in `block (3 levels) in start_threads'
App 6038 stderr: 	from /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:97:in `block in create_thread_and_abort_on_exception'
```

**Comment by itsderek23** [comment]
@swapnilabnave,

Sorry for the issues - this should be addressed in scout_apm version `2.0.0.pre2`.
