### ISSUE TITLE
Dependency on ActiveSupport?

### ISSUE THREAD

**Issue by Roguelazer** [scoutapp/scout_apm_ruby#467]
I'm using ScoutAPM with a Sinatra app (without ActiveSupport), and ScoutAPM is crashing with the following:

```
gems/scout_apm-5.3.3/lib/scout_apm/layer_converters/external_service_converter.rb:56:in `domain_name': undefined method `blank?' for "redacted":String

        domain = DEFAULT_DOMAIN if domain.to_s.blank?
                                              ^^^^^^^ (NoMethodError)
    from gems/scout_apm-5.3.3/lib/scout_apm/layer_converters/external_service_converter.rb:17:in `block in register_hooks'
    from gems/scout_apm-5.3.3/lib/scout_apm/layer_converters/depth_first_walker.rb:35:in `block (2 levels) in walk'
    from gems/scout_apm-5.3.3/lib/scout_apm/layer_converters/depth_first_walker.rb:35:in `each'
    from gems/scout_apm-5.3.3/lib/scout_apm/layer_converters/depth_first_walker.rb:35:in `block in walk'
    from gems/scout_apm-5.3.3/lib/scout_apm/layer_children_set.rb:67:in `block (2 levels) in each'
    from /app/vendor/ruby-3.2.1/lib/ruby/3.2.0/set.rb:511:in `each_key'
    from /app/vendor/ruby-3.2.1/lib/ruby/3.2.0/set.rb:511:in `each'
    from gems/scout_apm-5.3.3/lib/scout_apm/layer_children_set.rb:66:in `block in each'
    from gems/scout_apm-5.3.3/lib/scout_apm/layer_children_set.rb:65:in `each'
    from gems/scout_apm-5.3.3/lib/scout_apm/layer_children_set.rb:65:in `each'
    from gems/scout_apm-5.3.3/lib/scout_apm/layer_converters/depth_first_walker.rb:33:in `walk'
    from gems/scout_apm-5.3.3/lib/scout_apm/tracked_request.rb:341:in `record!'
    from gems/scout_apm-5.3.3/lib/scout_apm/synchronous_recorder.rb:27:in `record!'
    from gems/scout_apm-5.3.3/lib/scout_apm/tracked_request.rb:246:in `stop_request'
    from gems/scout_apm-5.3.3/lib/scout_apm/tracked_request.rb:136:in `stop_layer'
    from gems/scout_apm-5.3.3/lib/scout_apm/rack.rb:22:in `transaction'
    from /app/app.rb:18:in `block in <top (required)>'
```

Should scout_apm declare ActiveSupport as a direct dependency?

**Comment by mjobin-mdsol** [comment]
While ActiveSupport is pretty light and you can simply `require 'active_support/core_ext`' and not all of it.

I would still be tempted to fork to update this line ( if it's the only one ) in your suggestion.

ScoutAPM should definitely make it explicit or remove the dependency on it ...
