### ISSUE TITLE
Auto-Instrumentation creates syntax error

### ISSUE THREAD

**Issue by natematykiewicz** [scoutapp/scout_apm_ruby#484]
The auto-instrumentation patches do not work with Ruby 3 hashes that do not have a value.

This is perfectly valid Ruby 3.2.2 code in a Rails controller:
```ruby
def base_cache_key
  {
    path: request.env['PATH_INFO'],
    timestamp: (Time.now.to_i / 300),
    publishing_status:,
  }
end
```

Which causes this syntax error when deployed to production:

```
Nov 3 03:00:19 PM  bundler: failed to load command: puma (/app/vendor/bundle/ruby/3.2.0/bin/puma)
Nov 3 03:00:19 PM  /app/vendor/bundle/ruby/3.2.0/gems/scout_apm-5.3.5/lib/scout_apm/auto_instrument/instruction_sequence.rb:11:in `compile': /app/app/controllers/api/v4/experiences_controller.rb:86: syntax error, unexpected ':', expecting => (SyntaxError)
Nov 3 03:00:19 PM  ...che_key'"]){publishing_status}:,
Nov 3 03:00:19 PM  ...                              ^
Nov 3 03:00:19 PM
Nov 3 03:00:19 PM       from /app/vendor/bundle/ruby/3.2.0/gems/scout_apm-5.3.5/lib/scout_apm/auto_instrument/instruction_sequence.rb:11:in `load_iseq'
```

The workaround is to add a value to the Hash, even though it's not necessary anymore.

```ruby
def base_cache_key
  {
    path: request.env['PATH_INFO'],
    timestamp: (Time.now.to_i / 300),
    publishing_status: publishing_status,
  }
end
```

**Comment by jrothrock** [comment]
Which version of `parser` are you using?

**Comment by natematykiewicz** [comment]
@jrothrock 3.2.2.4 (the latest)

**Comment by kxmbrian** [comment]
This seems to be happening when the hash value is a method call.

**Comment by natematykiewicz** [comment]
That would align with my error as well. `publishing_status` is a method.

**Comment by kxmbrian** [comment]
I've taking a swipe at fixing it here: #486
