### ISSUE TITLE
undefined method `has_key?'

### ISSUE THREAD

**Issue by acrogenesis** [scoutapp/scout_apm_ruby#51]
I got this error after installing

```
undefined method `has_key?' for nil:NilClass (NoMethodError)
  ...../gems/ruby-2.3.1/gems/scout_apm-2.0.0.pre5/lib/scout_apm/config.rb:122:in `has_key?'
  ...../gems/ruby-2.3.1/gems/scout_apm-2.0.0.pre5/lib/scout_apm/config.rb:58:in `block in value'
  ...../gems/ruby-2.3.1/gems/scout_apm-2.0.0.pre5/lib/scout_apm/config.rb:57:in `each'
  ...../gems/ruby-2.3.1/gems/scout_apm-2.0.0.pre5/lib/scout_apm/config.rb:57:in `value'
  ...../gems/ruby-2.3.1/gems/scout_apm-2.0.0.pre5/lib/scout_apm/environment.rb:106:in `hostname'
  ...../gems/ruby-2.3.1/gems/scout_apm-2.0.0.pre5/lib/scout_apm/agent/logging.rb:31:in `format_message'
  ...../rubies/ruby-2.3.1/lib/ruby/2.3.0/logger.rb:434:in `add'
  ...../rubies/ruby-2.3.1/lib/ruby/2.3.0/logger.rb:507:in `error'
  ...../gems/ruby-2.3.1/gems/scout_apm-2.0.0.pre5/lib/scout_apm/agent/logging.rb:22:in `rescue in init_logger'
  ...../gems/ruby-2.3.1/gems/scout_apm-2.0.0.pre5/lib/scout_apm/agent/logging.rb:15:in `init_logger'
  ...../gems/ruby-2.3.1/gems/scout_apm-2.0.0.pre5/lib/scout_apm/agent.rb:115:in `start'
  ...../gems/ruby-2.3.1/gems/scout_apm-2.0.0.pre5/lib/scout_apm.rb:154:in `block in <class:Railtie>'
  ...../gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `instance_exec'
  ...../gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `run'
  ...../gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/initializable.rb:55:in `block in run_initializers'
  ...../rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
  ...../rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  ...../rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
  ...../rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
  ...../rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
  ...../rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
  ...../rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
  ...../rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
  ...../rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
  ...../gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/initializable.rb:54:in `run_initializers'
  ...../gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/application.rb:352:in `initialize!'
  ...../app/config/environment.rb:5:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  ...../gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
  ...../gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  ...../gems/ruby-2.3.1/gems/passenger-5.0.29/src/helper-scripts/rack-preloader.rb:110:in `eval'
  ...../gems/ruby-2.3.1/gems/passenger-5.0.29/src/helper-scripts/rack-preloader.rb:110:in `preload_app'
  ...../gems/ruby-2.3.1/gems/passenger-5.0.29/src/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  ...../gems/ruby-2.3.1/gems/passenger-5.0.29/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  ...../gems/ruby-2.3.1/gems/passenger-5.0.29/src/helper-scripts/rack-preloader.rb:29:in `<main>'
```

**Comment by itsderek23** [comment]
Apologies @acrogenesis. I believe this was occurring when a config file isn't present (like on Heroku). 

3e3e13a4606544a2e173828add38e424002c13fa attempts to address this. Try `bundle update scout_apm` to grab the latest (2.0.0.pre6).
